name: kampenies
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.4 <=4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.2
  http: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Kampenies_App
      fonts:
        - asset: assets/fonts/Kampenies_App.ttf

    - family: Satoshi
      fonts:
        - asset: assets/fonts/satoshi/Satoshi-Bold.otf
          weight: 800
        - asset: assets/fonts/satoshi/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/satoshi/Satoshi-Regular.otf
          weight: 400
