/// Flutter icons Kampenies_App
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Kampenies_App
///      fonts:
///       - asset: fonts/Kampenies_App.ttf
///
///
///
// ignore_for_file: camel_case_types, constant_identifier_names

import 'package:flutter/widgets.dart';

class Kampenies_App {
  Kampenies_App._();

  static const _kFontFam = 'Kampenies_App';
  static const String? _kFontPkg = null;

  static const IconData icon_konsultasi =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_beranda =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_media =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_profile =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
