/// Flutter icons Kampenies_App
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Kampenies_App
///      fonts:
///       - asset: fonts/Kampenies_App.ttf
///
///
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class Kampenies_Appp {
  Kampenies_Appp._();

  static const _kFontFam = 'Kampenies2';
  static const String? _kFontPkg = null;

  static const IconData book =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_bookmark =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
